### ISSUE TITLE
File browser

### ISSUE THREAD

**Issue by danielperna84** [jmart518/hass-poc-configurator#1]
Answering your [post from the community](https://community.home-assistant.io/t/simplistic-configuration-ui/10175/54?u=danielperna84) here to not spam the topic there:

Looking good. Do you also already have the logic for collapsing folders, or is this static html?
And what do you think about my idea with the mobile-like browser? If you solution just is a mockup the "simpler" browser I'm suggesting may be quicker to implement. I could do that.

Besides that: I would really like to merge a PR so I have a similar base for continuing my work. If I do to much there may be conflicts. So I'd see a greater priority for the settings and leave the tree as it is for now.

**Comment by jmart518** [comment]
Right now the folders collapse/expand on click and we can set whether or not we want them expanded by default (like the parent "Home Assistant" folder in the image)

I do like the idea of a more mobile-like browser, going to have to play with that

Sounds like a plan!  I am a total rookie to github still, do I just click on "New Pull Request"?

**Comment by danielperna84** [comment]
Yupp, that's what you need to do. I have created a dev-branch a second ago. Use that one for the PR. Otherwise everybody trying to install would get the mix of both. I'll finalize the dev-branch then and maki it public.

**Comment by jmart518** [comment]
Just to be safe I thought I better check with you before clicking "go" 
<img width="1017" alt="screen shot 2017-02-05 at 10 48 10 am" src="https://cloud.githubusercontent.com/assets/1509640/22628398/a172d796-eb90-11e6-8d25-ffa564afaae0.png">

**Comment by danielperna84** [comment]
Yes, that's how it should be. :)

**Comment by jmart518** [comment]
Merged, I hope I didn't kill anything ha!

**Comment by danielperna84** [comment]
No worries, I still have to merge it as well, and maybe ask for some changes before. I'll check it out now. :)

**Comment by danielperna84** [comment]
Ok, your code is merged. Working so far.

So to continue the work I would propse:

- You finish the settings menu (when you're done create another PR against the dev-branch)
- I'll make a new file browser

For the file browser I'm still unsure what your opinion is. Do you want to continue with the tree-version, or is the mobile-like version ok for you as well?

**Comment by jmart518** [comment]
Excellent, I'll get working on the settings menu today/tonight

I'll definitely be happy with either browser style.  The full tree makes for potentially faster file switching and navigating, but a mobile-like browser will clean up the interface quite a bit and eliminate endless scrolling in a large tree

**Comment by danielperna84** [comment]
Ok, then I'll go with the mobile-like version. :)

**Comment by jmart518** [comment]
Sounds great!

**Comment by danielperna84** [comment]
I'm finished with the filebrowser. I have already pushed everything into the [dev branch](https://github.com/danielperna84/hass-poc-configurator/tree/dev). The updated html is also in the confiurator.py, so you can test with using just that.

I have also fixed the old settings menu. It doesn't look as nice anymore as before, but functionality is pretty much at 100%. The only thing that's odd is that when clicking next to the menu to close it, the main content is still faded. A second click is needed to make the fading go aways.
Since I don't know how far you've come with the custom settings menu: should we stick with the original menu and try to fix the fading-problem?

And one minor "bug" in the filebrowser: the text of the elements is not vertically centered. I didn't dig deep enough to find a solution for that. And very long filenames are a problem. Maybe some overflow ellipsis will fix that. But I'll look at that tomorrow. 2:30 A.M. already and I need some sleep. :D

**Comment by jmart518** [comment]
Awesome!  I've made it pretty far on the custom menu, have a look

Everything works except the text_input and item_select elements, I could use some help with that logic.

<img width="321" alt="screen shot 2017-02-05 at 6 47 03 pm" src="https://cloud.githubusercontent.com/assets/1509640/22632103/aaccca5c-ebd3-11e6-9115-18b4d01b95a1.png">

**Comment by jmart518** [comment]
Ace settings menu is almost ready for prime time.

If you can, please take a look at my latest dev.html, I was able to figure out how to pass everything except for the input fields with numeric values (drag delay, font size, print margin column, scroll speed, tab size, and wrap limit).  Any pointers on how to pass this data?

I also added a small intro animation, let me know if you think it's too much

Talk to you tomorrow!

**Comment by danielperna84** [comment]
Have tested it. What I have noticed:

- Selecting the language / syntax does not work (other selects do as they should)
- The checkbox for showing the print margin behaves inverted

Besides that (and the numeric fields) it's great. Although I'd leave the animation out. People might use this on mobile devices, and who knows how those devices like such eye-candy.

I'll have a look now at the numeric fields. One thing though: I think we don't need most of them. Only the tab size and wrap limit seem useful to me. Changing the font size didn't work for me with the original editor either, and the other ones aren't that important. But since they are already there I'll fix those if I get it working.

**Comment by jmart518** [comment]
Good deal, I'll look into those issues.

This is what I came up with on the numeric fields, but it's still not working.  The value is definitly being passed, but it doesn't take effect.

HTML:
<div class="input-field col s12">
                    <input value="4" type="number" onchange="tab_value()" id="tab_size">
                    <label class="active" for="tab_size">Tab Size</label>
                </div>

Script:
    var tabs = document.getElementById("tab_size");

// Trying to get input values to work. . .
    function tab_value() {
        editor.setOption("tabSize", tabs);
    }

**Comment by jmart518** [comment]
``

**Comment by danielperna84** [comment]
This is how changing tab size works for me:

```
<input value="4" id="tab_size" type="number" onchange="editor.setOption('tabSize', this.value)">
```

One more thing:
You seem to have taken out the feature that editor settings are saved in a local storage. That's what the `localStorage.pochass = JSON.stringify(editor.getOptions())` in the `save_dialog`-function was for.

I'll create another branch where you can target your pull request at. My work with the filebrowser will cause conflicts. So I guess the cleanest way would be to merge your code to another branch, and I'll apply my changes on top of that.

**Comment by jmart518** [comment]
Wow, genius, I was making this way too complicated!

I'll take out most of those unnecessary non-working text-inputs.

Shoot, I don't recall seeing the local storage (other than in your IF). I was actually going to ask you if local storage was possible

Print Margin checkbox is now correct, still working on the language/syntax not working.  It looks like it should, but it's not. . . Very strange

**Comment by jmart518** [comment]
Ok I see where that function was, I was under the impression that it was to save your edits to the file.  Now if I'm reading it correctly it looks like it would save the Ace Settings as well as prompt to save the changes to the file, right?

**Comment by danielperna84** [comment]
Yes. I didn't take the time to add a dedicated dialog for saving editor settings. But now that we have a menu, my workaround can be left out if we instead have a button, maybe all the way at the bottom.

Oh, and I think renaming "Ace Keyboard" to "Keyborad Shortcuts" (or just "Shortcuts" if both word is to big) would make more obvious where it's taking the users.

**Comment by jmart518** [comment]
<img width="333" alt="screen shot 2017-02-06 at 2 22 50 pm" src="https://cloud.githubusercontent.com/assets/1509640/22666911/cb8be292-ec77-11e6-8494-349adaf58e83.png">
<img width="166" alt="screen shot 2017-02-06 at 2 22 38 pm" src="https://cloud.githubusercontent.com/assets/1509640/22666912/cb8f170a-ec77-11e6-80c9-630f3f3f2884.png">

**Comment by danielperna84** [comment]
Yes, that's perfect. :)

**Comment by jmart518** [comment]
Right on!

Rookie question: Now as far as the local storage saving goes, will this need to be called in a function or can I call it directly from an onclick?

localStorage.pochass = JSON.stringify(editor.getOptions())

**Comment by danielperna84** [comment]
Uhm, I actually don't know. But I think a dedicated function doesn't do any harm.

Oh, and another thing I've noticed: the keyboard handlers for `textarea` and `sublime` aren't hostet via CDN. So setting those fails. It was like that before already. But because of that you can take out those two options.

**Comment by jmart518** [comment]
Dedicated function it is:

`function save_ace_settings() {
        localStorage.pochass = JSON.stringify(editor.getOptions())
        Materialize.toast("Ace Settings Saved", 2000);
    }`

**Comment by jmart518** [comment]
This is the mobile view with confirmation:
![screen shot 2017-02-06 at 2 34 17 pm](https://cloud.githubusercontent.com/assets/1509640/22667317/8a7fd860-ec79-11e6-8caa-631f986fda82.png)

No errors in the console either, hmmm

**Comment by danielperna84** [comment]
I can't follow. Should there be an error?
Saving the settings just puts the data in the local storage. The next time you open the site it should look like you have left it. So when you switch the theme, save it, close the browser and then return, you should see the custom theme, along with the other settings like syntax etc.

**Comment by jmart518** [comment]
Nevermind, it does appear to be working in some areas, but not others.

Setting a theme and saving works, but the checkboxes are not being saved or are being overwritten on reload

**Comment by danielperna84** [comment]
That's probably because you hardcode defaults. I thought loading the settings would overwrite those. But in that case you could try leaving out the `checked`, `selected` and `value` parameters.

**Comment by jmart518** [comment]
So the more I mess with this, I believe it's saving, the real issue is that the checkboxes, selectors, and input_fields are not being populated with the actual values

**Comment by danielperna84** [comment]
If you commit your work I could have a look at it.

**Comment by jmart518** [comment]
Just pushed the update

Thanks, I appreciate you looking at it

**Comment by danielperna84** [comment]
You are correct. The settings are being loaded, but the input elements don't reflect their state. I'll think of an elegant solution for that.

What I've noticed: The checkboxes toggle isn't really ideal. Instead of
```html
<input type="checkbox" class="blue_check" onclick="toggle_animatedscroll()" id="anim_scroll" />
```
we could do
```html
<input type="checkbox" class="blue_check" onclick="editor.setAnimatedScroll(!editor.getAnimatedScroll())" id="anim_scroll" />
```

That would spare us from the extra function and variable. The only question the would be how to initially set the checkboxes checked or unchecked. I'll dig deeper.

**Comment by danielperna84** [comment]
This turns out to be rather tricky. I'm unsure if it's really worth the effort figuring out a solution when the packaged settings-menu is working with my fix. Sure, it's visually not as appealing and doesn't blend in that well. But the custom menu seems to require more complexity then I have originally thought. :(

**Comment by danielperna84** [comment]
Ok, if we stick to the custom settings menu, the functions to handle the setting-changes should at least be simplified. My proposal from above doen't work, but `editor.setAnimatedScroll(!editor.getAnimatedScroll())` works when it's put into the `toggle_animatedscroll()` function. That way we're not using hardcoded values anymore and can focus on syncing the UI, also by referencing the settings the editor-object provides.

Question: do you wan't to keep on working on this? For me it would be fine to just merge your work and figure something out. Since we're working on exactly the same file it's hard if we both mess with it. If that's ok with you, then you can create the pull request (against the branch I've created for you).

**Comment by jmart518** [comment]
That sounds good to me, would you like me to make the onclick changes before the pull request?

**Comment by danielperna84** [comment]
I have merged everything. Your last state + my modifications + new filebrowser can now be seen at https://github.com/danielperna84/hass-poc-configurator/tree/dev.
Still open to do is fixing the new settings menu. 'll take care of that.

Could you please test if this works for you? Especially the new filebrowser. Opening binary files of course won't work correctly, and you shouldn't save if you have opened one. Besides that all of your work is now integrated. :)

**Comment by jmart518** [comment]
Awesome, I'll check it out shortly!

Great work on this man, I can't wait to see what you come up with for the settings menu.  Nothing I've tried has worked like I wanted

**Comment by jmart518** [comment]
Observations so far:

New file browser is awesome!!

 - What do you think about having the sidenav close after clicking a file?
 - I vote to leave the fadeIn/slideIn left for the selectors since it will only be visible on large screens (no mobile).  It seems to give it a nice touch, let me know if you disagree.
 - Vertical alignment (which you've already meantioned) needs to be squared away
 - I'm wondering how the filebrowser would look without dividers and maybe a slightly larger height

I made a couple small tweaks to dev.html that I just pushed to my repo (with changes in comments)

**Comment by danielperna84** [comment]
- Had that turned on for a while, but found it annoying when "scrubbing" through files. Since the new browser allows to modify files systemwide, people might actually be searching for something to edit. Not Closing the panel then works as a kind of "preview", which I really like.
- I disagree, because it has now functional value. We can keep it in mind and ask if people would want that later on. We know how to implement if it it's asked for.
- Yes. But since that's minor and cosmetic that can be an issue we'll take care of some time later as well.
- I assume it wouldn't meet the Material Design "rules". Those dividers clearly separate elements from each other. And instead of increasing the hight I would actually rather decrease it. In a folder with a lot of files scrolling can seem "endless". For the first material release I would propose to stick with the official style guidelines.

I'll have a look at your changes. :)

**Comment by jmart518** [comment]
That all sounds good to me!

I think what's bothering me is the divider line maybe too dark.  I'm thinking a little lighter and it will do wonders to the view of the file browser

**Comment by danielperna84** [comment]
For now I think I'm pretty much done for a first release candidate. All the settings (restoring them) seem to work (except wrapping, which is tied to a current session). Simplified some stuff, and and some more content to the about-dialog.

If the current result is ok with you, I'll embed the dev.html into the new configurator.py and merge this with the master branch.

**Comment by jmart518** [comment]
Looks and acts great!  Well done on the settings menu too btw

The only thing I would say is to ditch lines 4, 5, and 12 as they are no longer needed

`    
    <meta name="theme-color" content="#EE6E73">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animate.css/3.5.2/animate.min.css">`

**Comment by danielperna84** [comment]
True. And done. :)

**Comment by jmart518** [comment]
Ok shoot I didn't test the language/syntax.  Did you already fix that?  My HA instance is rebooting

**Comment by danielperna84** [comment]
Yes, saving and changing works. While testing I've noticed it's not working. But all fixed now. :)

**Comment by jmart518** [comment]
Awesome!  This is a thing of beauty sir

**Comment by jmart518** [comment]
Oh wait, don't push final yet

**Comment by danielperna84** [comment]
Indeed. I'm totally in love with it. I'm a functionalist and usually don'T care to much about the visuals. But thanks to you this now is a really goog looking piece of software. :)

**Comment by jmart518** [comment]
Not a biggie, but there are a couple changes that would be nice to get in

Please see my dev.html

Updated jquery, not a show stopper if it's too late

**Comment by danielperna84** [comment]
Uhm, I can't tell the difference because it compares it to your old state. But I guess it's indeed no biggie and we'll just leave it as it is. I'll look if there's anything to be done with the readme and make a fresh screenshot. And then I'll do the new release. :)

**Comment by jmart518** [comment]
Sounds like a plan!

We can just make it part of the next release/patch

**Comment by danielperna84** [comment]
New release is out: [0.1.0](https://github.com/danielperna84/hass-poc-configurator/releases/tag/0.1.0)

Thanks again for your help. Much appreciated. :)

**Comment by jmart518** [comment]
Very cool, this has been a blast, can't wait to see where else this thing can go

**Comment by jmart518** [comment]
Fixed up the vertical positioning of the items in the file browser
<img width="355" alt="screen shot 2017-02-07 at 9 57 36 pm" src="https://cloud.githubusercontent.com/assets/1509640/22724012/895e3f64-ed80-11e6-804b-8e1eb19742ee.png">

I also changed up the About modal a little, what are your thoughts?
<img width="801" alt="screen shot 2017-02-07 at 9 57 24 pm" src="https://cloud.githubusercontent.com/assets/1509640/22724020/9bae10a4-ed80-11e6-9cc6-254ff3e0d7fb.png">

**Comment by jmart518** [comment]
Here's something else before I hit the sack, what do you think about something like this?  That way the user doesn't really ever leave the Configurator

<img width="1440" alt="screen shot 2017-02-08 at 12 41 17 am" src="https://cloud.githubusercontent.com/assets/1509640/22727774/f2db817e-ed97-11e6-9f54-1a533d144ed4.png">

**Comment by danielperna84** [comment]
Good work! :)
Regarding the components: It looks nice, but my personal behaivor is, that I tend to really browse around, maybe even opening new tabs etc.. On top of that, this might not work as well when used on mobile. So I think a new tab is more flexible and intuitive.

On important thing: The way it is now your repo is out of sync. This will happen a lot, and it's hard merging your changes, other than doing it manually. To tackle that problem you should have a look at [this](https://home-assistant.io/developers/development_catching_up/) article for HASS development. It should also apply to what we are doing.
If you want to take the easy route, make a local copy of your modified dev.html, completely delete your fork and create a new on. Then commit your backed up copy of dev.html, and only the effective changes compared to my repository will be displayed. With that we could then again do a pull request, this time without stashing to keep track of who has commited the changes.

Another thing I see: sometimes you rewrite JS objects to a form I've never seen before. The way I write them is how Python dictionaries are considered valid. So I'd like to keep them that way (`,` at  the end of the line, not the beginning).

**Comment by jmart518** [comment]
Thanks!

Ok, in my local copy I have it open a new tab when in mobile view, but when browsing on desktop it opens within Configurator.  Your tab/work flow sounds very similar to mine, but I ended up liking it much more than expeced.  The ability to quick view components and or any part of the HA website for that matter (it also keeps your place when you close and re-open it) is really slick.  Do you want to give it a go before I strip it out?  If so, I'll push it to my new repo in a little while.

I'll take a peek at that that article today and in the mean time, I'll squash this repo and fork the new.  I've been wondering how all this works, especially when things get way outta sync, as I've not used git for much of anything prior to this.

Shoot! I think I know why this is happening, since I really never need to touch the JS objects and when I do, I keep everything the same as yours.  My editor "beautifies" on save, so it's moving everything around.  Sorry about that, I've disabled it :)

**Comment by jmart518** [comment]
Closing this issue to delete repo.  Will re-fork latest
